services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8011:8011"
    volumes:
      - /home/yun/workspace/ncafe/backend/upload:/app/upload
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db.newlecture.com:5432/ncafedb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=ncafe
      - SPRING_DATASOURCE_PASSWORD=new_ibm2

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8011
    ports:
      - "3011:3011"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8011
    depends_on:
      - backend
